### ISSUE TITLE
cách dùng

### ISSUE THREAD

**Issue by acdev1508** [chuanghiduoc/locket-crack-ios#1]
này dùng như nào v bạn ơi

**Comment by chuanghiduoc** [comment]
Bạn dùng Shadowrocket rồi import cái đường link raw của file locket.sgmodule vào trong tệp cấu hình của Shadowrocket, sau đó nhấn vào sử dụng và chỉnh sửa cấu hình, trong này bạn vào phần Giải mã https rồi bật nó lên rồi cài chứng chỉ của nó vào máy, nhớ bật chứng chỉ trong càu đặt của máy lên nhé

![image](https://github.com/user-attachments/assets/b9d8bee5-a409-451f-992c-d22be28862ff)![image](https://github.com/user-attachments/assets/b718706b-b53d-45e3-81c1-e25cb92327f0)![image](https://github.com/user-attachments/assets/24102833-fb34-462f-a76d-0d41dac9860b)![image](https://github.com/user-attachments/assets/dcb7ee32-0982-4348-bd0f-80b073a0e7e8)
